apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-identity
  namespace: agro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-identity
  template:
    metadata:
      labels:
        app: postgres-identity
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: agro_identity
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-identity
  namespace: agro
spec:
  selector:
    app: postgres-identity
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
