apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: agro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
        - name: analysis-service
          image: rismair/agro-analysis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: InternalApi__Key
              value: "0123456789-0123456789"
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: MongoDB__ConnectionString
              value: mongodb://mongodb:27017
            - name: RabbitMQ__Host
              value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: agro
spec:
  selector:
    app: analysis-service
  ports:
    - name: http
      port: 80
      targetPort: 80
