global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'identity-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['identity-service:80']

  - job_name: 'properties-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['properties-service:80']

  - job_name: 'ingestion-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['ingestion-service:80']

  - job_name: 'analysis-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['analysis-service:80']
