name: Docker Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: rismair

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute short sha
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push identity-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Identity/AgroSolutions.Identity.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-identity:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-identity:${{ steps.vars.outputs.sha_short }}

      - name: Build & Push properties-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Properties/AgroSolutions.Properties.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-properties:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-properties:${{ steps.vars.outputs.sha_short }}

      - name: Build & Push ingestion-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Ingestion/AgroSolutions.Ingestion.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-ingestion:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-ingestion:${{ steps.vars.outputs.sha_short }}

      - name: Build & Push analysis-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Analysis/AgroSolutions.Analysis.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-analysis:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-analysis:${{ steps.vars.outputs.sha_short }}

      - name: Build & Push api-gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/ApiGateway/AgroSolutions.ApiGateway/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-apigateway:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/agro-apigateway:${{ steps.vars.outputs.sha_short }}
